name: Packaging

on:
  - push

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run black
        run: tox -e format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run flake8
        run: tox -e lint

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install tox
        run: python -m pip install tox

      - name: Run mypy
        run: python -m tox -e typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.13"
            toxenv: "py313"
          - version: "3.12"
            toxenv: "py312"
          - version: "3.11"
            toxenv: "py311"            
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run pytest
        run: tox -e ${{ matrix.python.toxenv }}

  build_source_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/*.tar.gz
            ./dist/*.whl
